name: "mergesAPI"
replicaCount: 1

images:
  PullSecrets: 
    name: kartingreg
  repository: genesisproject.azurecr.io/mergesapi
  tag: "latest"

service:
  type: ClusterIP
  ports:
  - name: http
    port: 3000

volume:
  -name: mergesAPI-volume
   mountPath: /usr/src/app/dist/config/
   secretName: azure-secret 
   shareName: system-genesis/ 
   type: azurefile

config:
  configmaps: 
    name: mergesAPI
